- name: erpnext
  hosts: erpnext
  become: yes
  become_method: sudo
  remote_user: '{{admin_username}}'
  gather_facts: False
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt-get -y install python'

- hosts: erpnext
  become: yes
  become_method: sudo
  remote_user: '{{admin_username}}'
  roles:
    - { role: common, tags: "common" }
    - { role: erpnext, tags: "erpnext" }
    - { role: end, tags: "end" }