# # 服务器前置任务(ubuntu使用)
- name: Preinstall-erpnext
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: Install Python
     raw: sudo apt update && sudo apt-get -y install python
     ignore_errors: True


# # 核心任务

- hosts: all
  become: yes
  become_method: sudo
  gather_facts: True
  roles:
    - { role: common, tags: "common" }
    - { role: erpnext, tags: "erpnext" }
    - { role: end, tags: "end" }
    
    