- name: Erpnext
  hosts: all
  become: yes
  become_method: sudo

  - name: 'erpnext_installmethod_selection'
    prompt: "Please select the installation method? \n
    1: Shell,可用\n
    2: Docker,待测试\n"
    private: no
    default: 1
  vars:
    erpnext_installmethod_select:
      '1': 'Shell'
      '2': 'Docker'

  erpnext_installmethod: "{{erpnext_installmethod_select[erpnext_installmethod_selection]}}"
  
  vars_files:
    - vars/main.yml, when: erpnext_installmethod == "Shell"
    - vars/docker.yml, when: erpnext_installmethod == "Docker"


  roles:
    - {role: role_common , tags: "role_common"}
    - {role: role_cloud , tags: "role_cloud"}
    - {role: role_docker , tags: "role_docker"}
    - {role: erpnext , tags: "erpnext", when: erpnext_installmethod == "Shell"}
    - {role: erpnext , tags: "erpnext", when: erpnext_installmethod == "Docker"}
    - {role: role_init , tags: "role_init"}
    - {role: role_preend , tags: "role_preend"}
    - {role: role_end , tags: "role_end"}

                                                                                               
