erpnext_db_password: "123456"
erpnext_db_type: "mariadb"

erpnext_meta:

  "11":
     mariadb_version: "10.3"
     nodejs_version: "12"
     redis_version: "5.0"
     erpnext_frappe_version: "11"
     erpnext_db_config: ""
     mariadb_configuration_default:
      - name: innodb-file-format
        value: barracuda
      - name: character-set-client-handshake
        value: FALSE
      - name: character-set-server
        value: utf8mb4
      - name: collation-server
        value: utf8mb4_unicode_ci

  "12":
     mariadb_version: "10.3"
     nodejs_version: "12"
     redis_version: "5.0"
     erpnext_frappe_version: "12"
     erpnext_db_config: "--db-host 127.0.0.1 --db-port 3306 --db-password erpnext_db_password --db-type erpnext_db_type"
     mariadb_configuration_default:
      - name: innodb-file-format
        value: barracuda
      - name: character-set-client-handshake
        value: FALSE
      - name: character-set-server
        value: utf8mb4
      - name: collation-server
        value: utf8mb4_unicode_ci
