# Major version list: edge(develop)、v12、v11.1.15、v11
erpnext_version: "edge"
frappe_version: "edge"

admin_username: "Administrator"
admin_password: "admin"

mariadb_host: "mariadb"
mariadb_root_password: "123456"

erpnext_clone_url: "https://github.com/frappe/frappe_docker.git"
nginx_prox_clone_url: "https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion.git"
