# prerequisites  
- name: Install requisite package
  shell: |
    apt install build-essential python3-setuptools
    pip3 install minimum
  when: ansible_os_family == "Debian"

- name: Install requisite package
  shell: |
    yum groupinstall "Development Tools" -y
    yum install python3 -y
  when: ansible_os_family == "RedHat" 

# download and run install.py
- name: Download install.py
  get_url:
    url: wget https://raw.githubusercontent.com/frappe/bench/develop/install.py
    dest: /tmp/install.py

- name: Run install.py
  shell: |
    cd /tmp;
    sudo python3 install.py --production  \
    --version {{erpnext_version}} \
    --python {{erpnext_python_version}} \
    --mysql-root-password {{erpnext_mysql_root_password}} \
    --admin-password {{erpnext_admin_password}} \
    --site {{erpnext_site_name}}

  

  