---
## install erpnext by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

#1. installation-pre  
- name: Added user for erpnext
  user:
    name: erpnext
    shell: /bin/bash
    home: /home/erpnext

# set environment variable
- name: Copy jdk_env to /etc/profile.d
  copy:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    mode: 0755
  with_items:
    - {src: erpnext_env.sh,dest: /etc/profile.d/erpnext_env.sh}
    - {src: erpnext.service,dest: /lib/systemd/system/erpnext.service}

# change file permissions
- name: change file permissions
  shell: |
    setfacl -R -m u:erpnext:rwx /data/wwwroot 
    setfacl -R -m u:erpnext:rwx /data/logs

#2. install bench 
- block:
  - name: Install bench
    pip: 
      name: frappe-bench
      executable: pip3 

#3. init frappe-bench,install erpnext,new site;  
  - name: Init frappe-bench and Install erpnext and New site 
    shell: |
      cd /data/wwwroot
      source /etc/profile.d/erpnext_env.sh
      bench init --frappe-branch version-{{erpnext_version}} --python /usr/bin/python3 frappe-bench
      cd /data/wwwroot/frappe-bench
      yarn install 
      ./env/bin/pip3 install -q -U -e frappe-bench/apps/frappe  --use-feature=2020-resolver
      test -d sites/erpnext && rm -rf  sites/erpnext
      bench new-site --db-host 127.0.0.1 --db-port 3306 --db-name {{erpnext_db_name}} --db-password {{erpnext_db_password}} --db-type {{erpnext_db_type}} --mariadb-root-password {{erpnext_db_root_password}} --admin-password {{erpnext_admin_password}} --no-mariadb-socket erpnext  --force
      bench get-app --branch version-{{erpnext_version}} erpnext 
      ./env/bin/pip3 install -e apps/erpnext/
      bench --site erpnext install-app erpnext
      bench setup nginx
    become_user: erpnext
    become_method: su

#4. other configure
- name: nginx configure
  shell: sudo cat /data/wwwroot/frappe-bench/config/nginx.conf |sudo tee /etc/nginx/conf.d/default.conf

- name: Restart service
  service: 
    name: '{{item}}'
    state: restarted
    enabled: yes
  with_items: 
    - nginx
    - erpnext

# - name: Remove mariadb_erpnext user accounts
#   mysql_user: 
#     login_user: root 
#     login_password: "{{erpnext_db_root_password}}"
#     login_unix_socket: /data/mysql/mysqld.sock
#     name: 'erpnext' 
#     host: '::1'
#     state: absent

- name: Change mariadb_erpnext user SUPER permission
  shell: echo "REVOKE ALL PRIVILEGES ON *.* FROM 'erpnext'@'%';GRANT ALL PRIVILEGES ON *.* TO 'erpnext'@'%' ;" |mysql -uroot -p{{erpnext_db_root_password}}

# create link
- name: Create link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
    force: yes
  with_items:
    - {src: /data/wwwroot/frappe-bench/config,dest: /data/config/erpnext_config}
    - {src: /data/wwwroot/frappe-bench/logs,dest: /data/logs/erpnext_logs}
     
#5. install bench manager(To do)

#6. check version and service state
- name: Check bench、erpnext、frappe version
  shell: | 
    source /etc/profile.d/erpnext_env.sh
    echo "bench_version:" $(bench --version)  |tee -a /data/logs/install_version.txt
    echo $(bench version)  |tee -a /data/logs/install_version.txt
  become_user: erpnext
  become_method: su
  args:
    chdir: /data/wwwroot/frappe-bench

- name: Check erpnext Service
  shell: systemctl status erpnext | grep Active*
  register: check_erpnext_service
  notify: check_erpnext_service

  
