---
# preparation before start-up
- name: Clone erpnext and rename dir
  shell: |
    git clone https://github.com/frappe/frappe_docker.git
    test -d "frappe_docker" && mv frappe_docker erpnext
  args:
    chdir: /data/wwwroot/ 
    
- name: Copy env for production 
  template:
    src:  .env
    dest: /data/wwwroot/erpnext/.env
    
# pull and run docker-compose
- name: Pull and run docker-compose
  shell:
    docker-compose up -d
  args:
    chdir: /data/wwwroot/erpnext
