---
- name: Added user for erpnext
  user:
    name: erpnext
    shell: /bin/bash
    home: /home/erpnext

# install bench 
- name: Install bench
  shell: sudo -H pip install frappe-bench

- name: copy mariadb configure file
  copy:
    src: my.cnf
    dest: /etc/my.cnf

- name: Restart mairadb
  service:
    name: mariadb
    state: restarted

# bench init 
- block:
  - name: Init bench 
    shell: |
      cd /home/erpnext
      export GIT_PYTHON_REFRESH=quiet
      bench init --frappe-branch version-{{erpnext_version}} frappe-bench
      frappe-bench/env/bin/pip install -q -U -e bench-frappe/apps/frappe  --use-feature=2020-resolver
      cd /home/erpnext/frappe-bench
      ./env/bin/pip install -e apps/frappe/
      nohup bench start &
      bench new-site --db-name {{erpnext_db_name}} --db-password {{erpnext_db_password}} --db-type "erpnext_db_type" --mariadb_root-password {{erpnext_db_root_password}} --admin-password {{erpnext_admin_password}} {erpnext_site_name}}               
    become_user: erpnext
    become_method: su

# install erpnext and nginx configure
  - name: Install erpnext
    shell: |
      cd /home/erpnext 
      export GIT_PYTHON_REFRESH=quiet
      bench get-app --branch version-{{erpnext_version}} erpnext
      bench --site {{erpnext_site_name}} install-app erpnext
      bench setup nginx
      ln -sf /home/erpnext/frappe-bench/nginx.conf /etc/nginx/conf.d/erpnext.conf
      systemctl restart nginx
    become_user: erpnext
    become_method: su 
  when: erpnext_python_version == "python2"



    
    
    

# instal bench manager
- name: download bench manager
  shell: 