---
# install erpnext by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"
  
- name: Added user for erpnext
  user:
    name: erpnext
    shell: /bin/bash
    home: /home/erpnext

# configure mariadb 
- name: copy mariadb configure file
  template:
    src: my.cnf.jinja2
    dest: /etc/my.cnf

- name: Restart mairadb
  service:
    name: mariadb
    state: restarted

#1. install bench 
- block:
  - name: Install bench
    shell: sudo -H pip3 install frappe-bench

#2. init and start bench
  - name: Init bench 
    shell: |
      cd /home/erpnext
      export GIT_PYTHON_REFRESH=quiet
      bench init --frappe-branch version-{{erpnext_version}} frappe-bench
      frappe-bench/env/bin/pip3 install -q -U -e frappe-bench/apps/frappe  --use-feature=2020-resolver
      cd /home/erpnext/frappe-bench
      ./env/bin/pip3 install -e apps/frappe/
      yarn install
      nohup bench start &              
    become_user: erpnext
    become_method: su

#3. install erpnext and new site
  - name: New site and Install erpnext
    shell: |
      cd /home/erpnext/frappe-bench
      export GIT_PYTHON_REFRESH=quiet
      test -d sites/site1.local && rm -rf  sites/site1.local
      bench new-site --db-name {{erpnext_db_name}} --db-password {{erpnext_db_password}} --db-type {{erpnext_db_type}} --mariadb-root-password {{erpnext_db_root_password}} --admin-password {{erpnext_admin_password}} {{erpnext_site_name}} 
      bench get-app --branch version-{{erpnext_version}} erpnext
      ./env/bin/pip3 install -e apps/erpnext/
      bench --site {{erpnext_site_name}} install-app erpnext
      bench setup nginx 
    become_user: erpnext
    become_method: su 

#4. other configure
- name: nginx configure
  shell: |
    test -f /etc/nginx/conf.d/default.conf && rm -rf /etc/nginx/conf.d/default.conf
    ln -sf /home/erpnext/frappe-bench/config/nginx.conf  /etc/nginx/conf.d/
    systemctl restart nginx

# # instal bench manager
# - name: download bench manager
  