---
- name: Added user for erpnext
  user:
    name: erpnext
    shell: /bin/bash
    home: /home/erpnext

#1. install bench 
- name: Install bench
  shell: sudo -H pip install frappe-bench

- name: copy mariadb configure file
  copy:
    src: my.cnf
    dest: /etc/my.cnf

- name: Restart mairadb
  service:
    name: mariadb
    state: restarted

#2. init and start bench
- block:
  - name: Init bench 
    shell: |
      cd /home/erpnext
      export GIT_PYTHON_REFRESH=quiet
      bench init --frappe-branch version-{{erpnext_version}} frappe-bench
      frappe-bench/env/bin/pip install -q -U -e frappe-bench/apps/frappe  --use-feature=2020-resolver
      cd /home/erpnext/frappe-bench
      ./env/bin/pip install -e apps/frappe/
      nohup bench start &              
    become_user: erpnext
    become_method: su
    failed_when: false

#3. install erpnext and new site
  - name: New site and Install erpnext
    shell: |
      cd /home/erpnext/frappe-bench
      export GIT_PYTHON_REFRESH=quiet
      test -d sites/site1.local && rm -rf  sites/site1.local
      bench new-site --db-name {{erpnext_db_name}} --db-password {{erpnext_db_password}} --db-type {{erpnext_db_type}} --mariadb-root-password {{erpnext_db_root_password}} --admin-password {{erpnext_admin_password}} {erpnext_site_name}} 
      bench get-app --branch version-{{erpnext_version}} erpnext
      bench --site {{erpnext_site_name}} install-app erpnext
      bench setup nginx 
    become_user: erpnext
    become_method: su 
  when: erpnext_python_version == "python2"

#4. other configure
- name: nginx configure
  shell: |
    ln -sf /home/erpnext/frappe-bench/nginx.conf /etc/nginx/conf.d/erpnext.conf
    systemctl restart nginx

# # instal bench manager
# - name: download bench manager
  