---
- block:
  - name: replace mariadb's configration file
    template:
      src: mariadb.cnf.j2
      dest: /etc/mysql/conf.d/mysql.cnf

  - name: restart mariadb
    service: 
      name: mysql  
      state: restarted 
      enabled: yes

  - name: update pip
    command: pip install --upgrade pip

  - name: add a linux user
    user:
      name: frappe
      shell: /bin/bash
      home: /home/frappe
  become: yes
  become_user: root

- block:
  - name: Download bench repo
    git:
      repo: https://github.com/frappe/bench
      dest: /home/frappe/bench-repo

  - name: Install bench
    pip: name={{ bench_repo_path }} extra_args='-e'
    become: yes
    become_user: root

  - name: python3 bench init for production
    command: bench init {{ bench_path }} --frappe-path {{ frappe_repo_url }} --frappe-branch {{ frappe_branch }} --python {{ python }}
    args:
      creates: "{{ bench_path }}"
      
  - name: change mariadb host
    shell:
      bench set-mariadb-host 127.0.0.1
    args:
      chdir: /home/frappe/frappe-bench

  - name: Add a site
    expect:
      command: bench new-site erpnext
      responses: 
        "password": "{{root_password}}"
      timeout: 300
    args:
      chdir: /home/frappe/frappe-bench

  - name: get apps
    command: 
      bench get-app erpnext https://github.com/frappe/erpnext
    args:
      chdir: /home/frappe/frappe-bench

  - name: Add apps
    command: 
      bench --site erpnext install-app erpnext
    args:
      chdir: /home/frappe/frappe-bench

  - name: generate nginx port forwarding file
    command:
      bench setup nginx
    args:
      chdir: /home/frappe/frappe-bench
  become: yes
  become_user: frappe

- block: 
  - name: add erpnext.service
    copy:
      src: erpnext.service
      dest: /etc/systemd/system/erpnext.service
      owner: root
      group: root
      mode: 0640

  - name: start erpnext.service
    service: name=erpnext.service  state=started  enabled=yes

  - name: delete default nginx configurationfile
    file: 
      path: /etc/nginx/conf.d/default.conf
      state: absent

  - name: generate soft link of nginx configrationfile
    file:
      src: /home/frappe/frappe-bench/config/nginx.conf
      dest: /etc/nginx/conf.d/default.conf
      owner: root
      group: root
      state: link

  - name: restart nginx
    service: name=nginx  state=restarted  enabled=yes    
  become: yes
  become_user: root

- name: bench update
  command: bench update --patch
  args:
    chdir: /home/frappe/frappe-bench
  become: yes
  become_user: frappe
